# Generated by Django 3.2.6 on 2021-09-19 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='instaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_img', models.ImageField(null=True, upload_to='upload')),
                ('user_email', models.EmailField(max_length=254)),
                ('user_detail', models.CharField(default='Deny to disclose', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_image', models.ImageField(null=True, upload_to='upload')),
                ('post_caption', models.CharField(max_length=100)),
                ('post_created', models.DateTimeField(auto_now_add=True)),
                ('post_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instagram_App.instauser')),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_data', models.TextField()),
                ('comment_date', models.DateTimeField(auto_now=True)),
                ('comment_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instagram_App.instauser')),
                ('parent_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_id', to='Instagram_App.posts')),
            ],
        ),
    ]
