# Generated by Django 3.2.6 on 2021-09-19 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instagram_App', '0002_auto_20210919_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='saved_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_posts', models.ManyToManyField(to='Instagram_App.posts')),
                ('saved_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instagram_App.instauser')),
            ],
        ),
    ]
